#######################
###  Glogal Config  ###
#######################


# world config
path_config_world: 'H:\Documents\projets\LifeSim\configs\config_world.yaml'
# agent config
path_config_agent: 'H:\Documents\projets\LifeSim\configs\config_agent.yaml'
# display config
path_config_display: 'H:\Documents\projets\LifeSim\configs\config_display.yaml'

