
### Initial condition
n_agents: 150
n_food_spawns: 10

### Speciation
speciation_cutoff: 4.0

### Food
food:
  spawn_freq: 500
  spawn_rate: 0.000005
  energy: 400
  size: 3
  color: [250, 200, 0]

### World
worldgen:
  # scale
  height: 2000 #1440
  width: 3000 #2560
  grid_cell_size: 60
  # biomes
  noise_map: {scale: 0.0003, octaves: 3}
  biomes: 
    dense: {spawn_order: 1, spawn_rate: 0.25, food_spawn_rate_factor: 2.0, food_energy_factor: 0.5, color: [0, 90, 0]}
    normal: {spawn_order: 2, spawn_rate: 0.1, food_spawn_rate_factor: 1.0, food_energy_factor: 1.0, color: [0, 60, 0]}
    sparse: {spawn_order: 3, spawn_rate: 0.2, food_spawn_rate_factor: 0.25, food_energy_factor: 6.0, color: [0, 30, 0]}
    void: {spawn_order: 4, spawn_rate: 1., food_spawn_rate_factor: 0., food_energy_factor: 0., color: [0, 0, 0]}



