
### World
height: 1500 #1440
width: 1500 #2560
grid_cell_size: 50

### Biome
biome:


### Food
food_update_step_freq: 100
food_spawn_rate_per_pixel: 0.00008
food_energy: 100
food_size: 1
food_initial_n_step: 20

### Agent
n_agent: 70
speciation_cutoff: 4.0

