

initial_mutation_scale: 5

### Brain
brain:
  type: 'conditional'
  # TODO


### DNA
dna:
  mutation_scale: 0.1
  reproduction: 'clone' # 'mate' / 'clone'
  merge_mode: 'mean'  # 'mean' / 'rdm_choice'
  genes: 
    morphology: {type: 'continuous', value: 1., min: 0.1, max: None, mutable: True, mutation_factor: 1.}
    #physiology: {type: 'continuous', value: 1., min: 0.1, max: None, mutable: True, mutation_factor: 1.}
    sensorial: {type: 'continuous', value: 1., min: 0.1, max: None, mutable: True, mutation_factor: 1.}
  attributes:
    # physical
    size:  {min: 1, max: None, factor: 3, expr: "morphology**0.5"}
    speed: {min: 0.01, max: None, factor: 0.2, expr: "1 / morphology**0.5"}
    # behavioral
    aggressive: {min: 0, max: 1, factor: 0.0, expr: "1"}
    social: {min: 0, max: 1, factor: 0.0, expr: "1"} # TODO
    partner_dna_distance: {min: 1, max: None, factor: 4, expr: "1"}
    # physiological (attack & defense)
    max_health: {min: 1, max: None, factor: 10, expr: "1"}
    regeneration: {min: 0, max: 0.5, factor: 0.01, expr: "1"}
    damage: {min: 0, max: None, factor: 2, expr: "1"}
    # physiological (energy & mating)
    lifespan: {min: 1, max: None, factor: 2000, expr: "morphology"} # changed from  morphology**0.25 * physiology**0.75
    max_energy: {min: 1, max: None, factor: 1000, expr: "morphology"}
    energy_to_reproduce: {min: 1, max: None, factor: 500, expr: "morphology**0.75"}
    maturity_age: {min: 1, max: None, factor: 500, expr: "morphology**0.5"}
    reproduce_cooldown: {min: 1, max: None, factor: 500, expr: "morphology**0.5"}
    # alimentation
    max_satiety: {min: 0, max: None, factor: 200, expr: "1"}
    satiety_gain: {min: 0, max: 1, factor: 0.2, expr: "1"}
    metabolism_efficiency: {min: 0, max: 1, factor: 0.8, expr: "1"}
    # TODO eating_speed
    # sensory
    vision_range: {min: 1, max: None, factor: 50, expr: "sensorial**0.5"}
    # energy costs
    step_cost: {min: 0.0001, max: None, factor: 0.1, expr: "morphology**0.5"}
    sense_cost: {min: 0.0001, max: None, factor: 0.1, expr: "sensorial"}
    idle_cost: {min: 0.0001, max: None, factor: 0.01, expr: "morphology"}

    
      
